
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlidCWm6USX_Ho9J9jD5-Rfpe0Ni3eV_8',
    appId: '1:959525324636:web:92b62eaee872be5f7ca399',
    messagingSenderId: '959525324636',
    projectId: 'flutter-todo-lab',
    authDomain: 'flutter-todo-lab.firebaseapp.com',
    storageBucket: 'flutter-todo-lab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYS4MHi4lX1xOY2ODo4Gixbm7Z-J04ERo',
    appId: '1:959525324636:android:f80957cea75b8a4e7ca399',
    messagingSenderId: '959525324636',
    projectId: 'flutter-todo-lab',
    storageBucket: 'flutter-todo-lab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB_4gwCK9oA4xUDapj1ITrnVuv9tr6sKY',
    appId: '1:959525324636:ios:880a0c97c631f0fd7ca399',
    messagingSenderId: '959525324636',
    projectId: 'flutter-todo-lab',
    storageBucket: 'flutter-todo-lab.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB_4gwCK9oA4xUDapj1ITrnVuv9tr6sKY',
    appId: '1:959525324636:ios:880a0c97c631f0fd7ca399',
    messagingSenderId: '959525324636',
    projectId: 'flutter-todo-lab',
    storageBucket: 'flutter-todo-lab.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlidCWm6USX_Ho9J9jD5-Rfpe0Ni3eV_8',
    appId: '1:959525324636:web:e216dd0d7288902c7ca399',
    messagingSenderId: '959525324636',
    projectId: 'flutter-todo-lab',
    authDomain: 'flutter-todo-lab.firebaseapp.com',
    storageBucket: 'flutter-todo-lab.appspot.com',
  );
}
